##Numpy array operations

Lets first see how arrays behave like “vectors/matrices” when operations happen element-wise.

In [11]:
import numpy as np

arr = np.array([6,7,8,9,4])
arr2 = np.array([1,2,3,4,5])

These things are already different from List and if we talk about one more special power it is **Broadcasting**

In [12]:

matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix +5)
print(matrix -5)
print(matrix *5)
print(matrix /5)
print(matrix%5)
print(matrix//5)
print(matrix**5)


[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[[-4 -3 -2]
 [-1  0  1]
 [ 2  3  4]]
[[ 5 10 15]
 [20 25 30]
 [35 40 45]]
[[0.2 0.4 0.6]
 [0.8 1.  1.2]
 [1.4 1.6 1.8]]
[[1 2 3]
 [4 0 1]
 [2 3 4]]
[[0 0 0]
 [0 1 1]
 [1 1 1]]
[[    1    32   243]
 [ 1024  3125  7776]
 [16807 32768 59049]]


Even these things work with different shaped array the calculations will happen on every row. but dimensions must match

In [13]:
print(arr+arr2)
print(arr-arr2)
print(arr*arr2)
print(arr/arr2)
print(arr%arr2)
print(arr//arr2)
print(arr**arr2)

[ 7  9 11 13  9]
[ 5  5  5  5 -1]
[ 6 14 24 36 20]
[6.         3.5        2.66666667 2.25       0.8       ]
[0 1 2 1 4]
[6 3 2 2 0]
[   6   49  512 6561 1024]


#Aggregate Functions

These functions are used to calculate the statistics on arrays.

In [18]:
arr = np.array([10,20,30,40])
print(np.sum(arr))
print(np.min(arr))
print(np.max(arr))
print(np.mean(arr))
print(np.std(arr))
print(np.var(arr))

100
10
40
25.0
11.180339887498949
125.0


You can also do the axis based operations row-Wise and Colum-wise

In [21]:
mat = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]]
    )
print(np.mean(mat,axis=0))
print(np.mean(mat,axis=1))
print(np.sum(mat,axis=1))

[4. 5. 6.]
[2. 5. 8.]
[ 6 15 24]
