##1. Attributes of an Array

Introduce attributes that describe the array.

Attributes: .shape, .ndim, .size, .dtype.

In [3]:
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)
3
12
int64


##Indexing and Slicing
Now we have Indexing and slicing aswell and for that we are going to see 1d and 2d indexing lets start with **1D indexing** and it is similar to list.

In [8]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr[0])
print(arr[-1])


1
10


Now lets see the 2D indexing aswell

In [9]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0])
print(arr[-1])

[1 2 3 4 5]
[ 6  7  8  9 10]


In [10]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[0])


[[1 2 3]
 [4 5 6]]


Now we can also do the slicing lets see the **slicing in 1D**

In [11]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr[::-1])

[10  9  8  7  6  5  4  3  2  1]


1D slicing was really easy now lets see the **slicing in 2D**

In [12]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2,0:3])

[[1 2 3]
 [6 7 8]]


There is one more thing known as **Boolean indexing**

In [4]:
arr = np.array([10,20,30,40,15,25,17,12,13])
print(arr>15)

[False  True  True  True False  True  True False False]


In [5]:
arr = np.array([10,20,30,401])
print(arr>15)
print(arr[arr>15])

[False  True  True  True]
[ 20  30 401]


## Reshaping the Array

you can also reshape the Array as you like but be accurate about the dimensions

In [9]:
arr = np.arange(1,11).reshape(2,5)
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


## Flattening of an array

you can convert the 2D array to 1D using the Flattening Function

In [10]:
arr.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])