##Fancy Indexing
you can Pick elements from specific positions using a list/array of indices.

In [1]:
import numpy as np 
arr = np.array([1,3,4,5,9])
print(arr[0])
print(arr[[0,2,3]])

1
[1 4 5]


You can do this fancy indexing in 2D Matrix aswell

In [12]:
arr = np.array([[1,2,4],[5,6,7]])
print(arr[[1,0],[1,2]])
print(arr[0,1])

[6 4]
2


##Conditional Selection
Find values based on conditions or replace them.

In [7]:
arr = np.array([12,13,80,56,78,45,89,33,45,67,26])

np.where(arr>15,arr,6)



array([ 6,  6, 80, 56, 78, 45, 89, 33, 45, 67, 26])

##Sorting & Ordering
np.sort() → returns sorted array

np.argsort() → returns indices of sorted order

In [9]:
arr = np.array([5,3,4,9,7,2,1,85,34,56,78])
np.sort(arr)
np.argsort(arr)

array([ 6,  5,  1,  2,  0,  4,  3,  8,  9, 10,  7])

##Concatenation & Stacking

In [11]:
arr1 = np.array([2,3,4])
arr2 = np.array([5,6,7])

np.concat([arr1,arr2])

array([2, 3, 4, 5, 6, 7])

Vertical & Horizontal Stacking