# **Using NumPy**

Once you've installed NumPy you can import it as a library:

In [2]:
import numpy as np

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [3]:
lis = [1,2,3,4]
arr = np.array(lis)
arr

array([1, 2, 3, 4])

Lets create a matrix using list

In [4]:
lis = [[1,2,3],[4,5,6],[7,8,9]]
arr = np.array(lis)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Now lets see how matlix looks like using numpy arrays

In [10]:
matrix = np.array([[1,2,3,4],[5,6,7,12],[8,9,10,11]])
matrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7, 12],
       [ 8,  9, 10, 11]])

## Built-in Methods

there are lots of build in methods to create an array lets create some and see

np.zeros(), np.ones(), np.full()

np.arange(), np.linspace()

np.eye()

In [11]:
arr = np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [14]:
arr = np.ones([5,3])
arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [21]:
arr = np.full([5,5],10)
arr

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [23]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
arr = np.linspace(1,10,5)
arr

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [27]:
arr = np.eye(5)
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
arr = np.random.rand(5)
arr

array([0.5691224 , 0.57317614, 0.99284373, 0.12665127, 0.30670579])

In [33]:
arr = np.random.randint(1,10,5)
arr

array([4, 2, 4, 4, 5])

In [38]:
arr = np.random.rand(2,5)
arr

array([[0.60269232, 0.3812717 , 0.11142596, 0.13966009, 0.91932544],
       [0.44181983, 0.26522468, 0.37892992, 0.58159003, 0.4165543 ]])

arange → step-based values

linspace → fixed number of values

eye → identity matrix

rand → random floats (0–1)

randint → random integers in a range

randn → random values from bell curve distribution

In [7]:
arr = np.arange(1,5)
arr

array([1, 2, 3, 4])